In [9]:
import numpy as np
import pandas as pd
import os

def get_filename(number: int) -> str:
    try:
        for i in os.listdir("data"):
            keyword = str(number)+"_"
            if i[-3:] == 'csv' and i.startswith(keyword):
                filename = i # Only One!
        return filename
    except Exception:
        return 'NAN'

def data_processing(number: int) -> pd.DataFrame:
    '''
    para:
        number of subject
    '''
    k = get_filename(number)
    if get_filename(number) == 'NAN':
        return 'NAN'    
    else:
        filename = "data/"+ k 
    return filename

# raw_data = data_processing(432132)[1:]
# raw_data
def raw_data_exange(number: int) -> pd.DataFrame:
    flname = data_processing(number)
    x = ''
    with open(flname,'r+', encoding='utf-8') as file:
        x = file.read()
        x = x.replace('\n\n','').replace('，\n','，').replace('？\n','')
    file.close()

    with open(flname,'w', encoding='utf-8') as file2:
        file2.write(x)
    file2.close()

    raw_data = pd.read_csv(flname)
    return raw_data
raw_data = raw_data_exange(11)[1:-1]
raw_data = raw_data[raw_data['back'] != 'None'].reset_index()
raw_data = raw_data.drop(columns=['Mtext','Ftext','hint','index'])
# raw_data.head()
# raw_data.to_csv(flname)

In [116]:
def data_cut(df, back, emotion):
    df = df[df['emotion'] == emotion]
    df = df[df['back'] == back]

    df = df[df['corrAns'] != 'None' ]  # delete practice data or instruct items
    df = df.dropna(subset=['key_2.corr'])

    return df
r_data = data_cut(raw_data, '2-back', 'negative')
r_data

,back,emotion,plocation,tlocation,length,sign,corrAns,Pic,trials_2.thisRepN,trials_2.thisTrialN,...,key_resp_4.started,key_resp_4.keys,key_resp_4.rt,participant,session,date,expName,psychopyVersion,frameRate,Unnamed: 86
133,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,k,source/negative/3060.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
134,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,k,source/negative/9045.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
135,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,¤ #,s,source/negative/1200.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
136,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,¤ #,s,source/negative/9594.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
137,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,¤ #,k,source/negative/6312.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
138,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,£ ‡,s,source/negative/9921.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
139,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,s,source/negative/2100.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
140,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,£ ‡,k,source/negative/9010.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
141,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,k,source/negative/1274.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
142,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,s,source/negative/3301.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
143,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ ‡,s,source/negative/6260.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
144,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,k,source/negative/3110.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
145,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ ‡,k,source/negative/6836.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
146,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,¥ §,s,source/negative/1051.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
147,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,¥ §,s,source/negative/9102.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
148,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,s,source/negative/2661.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
149,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,s,source/negative/3180.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
150,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,k,source/negative/9180.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
151,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,k,source/negative/6510.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN
152,2-back,negative,practice_nag_2.xlsx,nag_2.xlsx,22,§ £,k,source/negative/9810.JPG,0.0,4.0,...,NaN,NaN,NaN,0,1,2022-11-19_20h04.17.030,Lab5_Emotional_NBack_Task,2022.2.4,165.414205,NaN

In [117]:
r_data['key_2.corr'].sum()

9.0

In [118]:
raw_data.columns

Index(['back', 'emotion', 'plocation', 'tlocation', 'length', 'sign',
       'corrAns', 'Pic', 'trials_2.thisRepN', 'trials_2.thisTrialN',
       'trials_2.thisN', 'trials_2.thisIndex', 'trials.thisRepN',
       'trials.thisTrialN', 'trials.thisN', 'trials.thisIndex',
       'trials_3.thisRepN', 'trials_3.thisTrialN', 'trials_3.thisN',
       'trials_3.thisIndex', 'confirm.started', 'text.started', 'confirm.keys',
       'confirm.rt', 'confirm_2.started', 'text_2.started', 'confirm_2.keys',
       'confirm_2.rt', 'Pre_instruction.started', 'pre_2.started',
       'pre_2.keys', 'pre_2.rt', 'text_3.started', 'key.started',
       'key.stopped', 'hintext.started', 'hintext.stopped',
       'Leftlabel.started', 'Leftlabel.stopped', 'Rightlabel.started',
       'Rightlabel.stopped', 'image.started', 'text_3.stopped',
       'image.stopped', 'key.keys', 'key.corr', 'feedback_01.started',
       'feedback_01.stopped', 'key.rt', 'confirm_3.started', 'text_4.started',
       'confirm_3.keys', 'confirm_3.rt', 'text_6.started', 'key_2.started',
       'key_2.stopped', 'Leftlabel_2.started', 'Leftlabel_2.stopped',
       'Rightlabel_2.started', 'Rightlabel_2.stopped', 'hintext_2.started',
       'hintext_2.stopped', 'image_2.started', 'text_6.stopped',
       'image_2.stopped', 'key_2.keys', 'key_2.corr', 'key_2.rt',
       'text_7.started', 'text_7.stopped', 'key_resp_5.started',
       'key_resp_5.stopped', 'key_resp_5.keys', 'text_11.started',
       'key_resp_4.started', 'key_resp_4.keys', 'key_resp_4.rt', 'participant',
       'session', 'date', 'expName', 'psychopyVersion', 'frameRate',
       'Unnamed: 86'],
      dtype='object')

In [129]:
import pandas as pd
names = ['subject_num','1_back_pos_corr','1_back_pos_rt','1_back_neu_corr','1_back_neu_rt','1_back_neg_corr','1_back_neg_rt','2_back_pos_corr','2_back_pos_rt','2_back_neu_corr','2_back_neu_rt','2_back_neg_corr','2_back_neg_rt','3_back_pos_corr','3_back_pos_rt','3_back_neg_corr','3_back_neg_rt','avg_whole_cor','avg_whole_rt']
dframe = pd.DataFrame(data=None,columns=names)
# dframe.to_csv('subjects_results.csv',index=False)

In [142]:
dframe

Empty DataFrame
Columns: [subject_num, 1_back_pos_corr, 1_back_pos_rt, 1_back_neu_corr, 1_back_neu_rt, 1_back_neg_corr, 1_back_neg_rt, 2_back_pos_corr, 2_back_pos_rt, 2_back_neu_corr, 2_back_neu_rt, 2_back_neg_corr, 2_back_neg_rt, 3_back_pos_corr, 3_back_pos_rt, 3_back_neg_corr, 3_back_neg_rt, avg_whole_cor, avg_whole_rt]
Index: []

In [178]:
data = [[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]]
m = pd.DataFrame(data=data, columns=dframe.columns)
m

,subject_num,1_back_pos_corr,1_back_pos_rt,1_back_neu_corr,1_back_neu_rt,1_back_neg_corr,1_back_neg_rt,2_back_pos_corr,2_back_pos_rt,2_back_neu_corr,2_back_neu_rt,2_back_neg_corr,2_back_neg_rt,3_back_pos_corr,3_back_pos_rt,3_back_neg_corr,3_back_neg_rt,avg_whole_cor,avg_whole_rt
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19

In [179]:

exp = pd.DataFrame(columns=dframe.columns, data=data)

index = 0 
full_value = 1 # discard Subject Number
while True:

    print('被试编号(Subject Number)： '+str(1)+'\n')
    print("组块数Block: "+str(index+1)+"\n")
    # print("组块信息(Block information): "+self.labels_explain[index]+'\n') 
    print("您在该组块的平均准确率为 (Your accurancy rate is): "+str(exp.iloc[:,full_value].tolist()[0])+"\n")
    full_value += 1
    print("您在该组块的平均反应时为(单位：秒)(Your average reaction time is): "+str(exp.iloc[:,full_value].tolist()[0])+"\n\n")
    full_value += 1
    index += 1
    if  full_value == len(exp.columns) -2:
        break
print("\n总体结果(WHOLE RESULTS): \n")
print("您在总体平均准确率为(Your whole accurancy rate is): "+str(exp['avg_whole_cor'].tolist()[0])+"\n")
print("您的总体平均反应时为(单位：秒)(Your whole average reaction time is  [s]): "+str(exp['avg_whole_rt'].tolist()[0])+"\n")




# input:   1 2 3 4 5 6
# output:  [1,2] [3,4] [5,6] [7.8] [9,10], []
# for index in range(1 , number):
#     print(index, dframe.columns[int(index/2)+1], dframe.columns[int(index/2)+2])

被试编号(Subject Number)： 1

组块数Block: 1

您在该组块的平均准确率为 (Your accurancy rate is): 2

您在该组块的平均反应时为(单位：秒)(Your average reaction time is): 3


被试编号(Subject Number)： 1

组块数Block: 2

您在该组块的平均准确率为 (Your accurancy rate is): 4

您在该组块的平均反应时为(单位：秒)(Your average reaction time is): 5


被试编号(Subject Number)： 1

组块数Block: 3

您在该组块的平均准确率为 (Your accurancy rate is): 6

您在该组块的平均反应时为(单位：秒)(Your average reaction time is): 7


被试编号(Subject Number)： 1

组块数Block: 4

您在该组块的平均准确率为 (Your accurancy rate is): 8

您在该组块的平均反应时为(单位：秒)(Your average reaction time is): 9


被试编号(Subject Number)： 1

组块数Block: 5

您在该组块的平均准确率为 (Your accurancy rate is): 10

您在该组块的平均反应时为(单位：秒)(Your average reaction time is): 11


被试编号(Subject Number)： 1

组块数Block: 6

您在该组块的平均准确率为 (Your accurancy rate is): 12

您在该组块的平均反应时为(单位：秒)(Your average reaction time is): 13


被试编号(Subject Number)： 1

组块数Block: 7

您在该组块的平均准确率为 (Your accurancy rate is): 14

您在该组块的平均反应时为(单位：秒)(Your average reaction time is): 15


被试编号(Subject Number)： 1

组块数Block: 8

您在该组块的平均准确率为 (Your accurancy rate is): 16

您在该组块的平均反应时为(单位：秒)(Your average reaction time is): 17



总体结果(WHOLE RESULTS):

您在总体平均准确率为(Your whole accurancy rate is): 18

您的总体平均反应时为(单位：秒)(Your whole average reaction time is  [s]): 19

,subject_num,1_back_pos_corr,1_back_pos_rt,1_back_neu_corr,1_back_neu_rt,1_back_neg_corr,1_back_neg_rt,2_back_pos_corr,2_back_pos_rt,2_back_neu_corr,2_back_neu_rt,2_back_neg_corr,2_back_neg_rt,3_back_pos_corr,3_back_pos_rt,3_back_neg_corr,3_back_neg_rt,avg_whole_cor,avg_whole_rt
0,10.0,0.9,0.675794,0.95,0.565388,1.0,0.706028,0.85,1.100756,0.75,1.259185,0.9,0.997121,0.75,1.266655,0.5,1.389508,0.825,0.950537

In [4]:
import pandas as pd
x = pd.read_csv("subjects_results.csv")
y = pd.read_csv("subjects_results_online.csv")


nc = pd.concat([x, y])
nc

nc.to_csv("subjects_results_online.csv", index=False)